//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RentService
{
    using System;
    using System.Collections.Generic;
    
    public partial class Car
    {
        public string Number { get; set; }
        public string Brand { get; set; }
        public int Cost { get; set; }
        public int CostPerDay { get; set; }
        public string Type { get; set; }
    }
}
